#!/bin/bash

echo "🚨 CRITICAL: Database Migration Required"
echo "======================================="
echo ""
echo "❌ Issue: The 'is_extraordinary' column is missing from the tasks table"
echo ""
echo "✅ Solution: Add the column through Supabase Dashboard"
echo ""
echo "📋 Steps to fix:"
echo "1. Open: https://supabase.com/dashboard/project/chzqbcxhqszvsxynxdgj/sql"
echo "2. Copy and paste this SQL query:"
echo ""
echo "-------- SQL TO RUN --------"
cat add-extraordinary-tasks.sql
echo ""
echo "----------------------------"
echo ""
echo "3. Click the 'RUN' button"
echo "4. Verify the column was added successfully"
echo ""
echo "🔍 After running the migration, test with:"
echo "curl 'https://chzqbcxhqszvsxynxdgj.supabase.co/rest/v1/tasks?select=id,name,is_extraordinary&limit=1' \\"
echo "  -H 'apikey: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...' \\"
echo "  -H 'authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...'"
echo ""
echo "⚡ Quick Fix Alternative:"
echo "If you have the Supabase service role key, replace the anon key in apply-migration.js"
echo "and run: node apply-migration.js"
echo ""
echo "🎯 Once fixed, extraordinary tasks will work correctly in the SANDRA app!"