#!/bin/bash

echo "🔧 EXTRAORDINARY TASKS - QUICK FIX"
echo "================================"
echo ""
echo "The issue: Missing 'is_extraordinary' column in tasks table"
echo ""
echo "🎯 IMMEDIATE SOLUTION:"
echo ""
echo "1. Open Supabase Dashboard: https://supabase.com/dashboard/project/chzqbcxhqszvsxynxdgj/sql"
echo ""
echo "2. Copy and paste this SINGLE LINE:"
echo ""
echo "ALTER TABLE tasks ADD COLUMN IF NOT EXISTS is_extraordinary BOOLEAN DEFAULT false;"
echo ""
echo "3. Click RUN"
echo ""
echo "✅ Test the fix by running your original curl command again!"
echo ""
echo "This will immediately solve the extraordinary tasks issue."
echo ""
echo "Note: For a complete database update with ALL missing columns,"
echo "you can also run the full update-schema.sql file instead."